### ISSUE TITLE
Final report draft feedback

### ISSUE THREAD

**Issue by rossbar** [berkeley-stat159/project-alpha#137]
Sorry --- I skipped you guys originally since you got a lot of time with Jarrod and Matthew on Tuesday. Here's my feedback from the paper:                                                        
- The introduction is very good: you present your plan in a clear and it is  
  apparent you developed it in a very methodical way.  
- I'm a little confused as to what the table in figure 2 is displaying.  
  Neither the text nor the caption really clarify what is being  
  shown, especially with regards to "accuracy". Maybe it would make more  
  sense if I stared at it longer, but consider polishing this part up.  
- For section 3.2.3 - if you have results from this (maybe one figure showing  
  the different HRF's convolved with the event course and what the resulting  
  columns in the design matrix look like) I'd be interested to see it; though  
  it is by no means necessary.  
- I didn't comment on any grammar mistakes as I assume you'll proofread before 
  submitting, but the first paragraph of section 3.3 has a typo regarding  
  regressors as "rows" of your design matrix  
- In figure 5 in your results section, is the y-axis ennumeration meaningful?  
  It looks like you just wanted to plot the lines on the same plot so chose  
  to set the baselines at increments of -2. If this is the case, you can  
  suppress the printing of the y-tick marks. If the values on the y-axis  
  are indeed meaningful, you should mention it either in the caption or  
  text.  
- Also, I'm not clear exactly what you are showing in figures 3 and 4 - try  
  to clarify what these images show. It's clear they are from a single voxel,  
  but what are the "fitted values" in this case? Is this the application of  
  your linear model to that voxel?  
- overall you do a very good job of explaining the logical thought processes  
  that went into your decisions. I very much appreciate this.

**Comment by benjaminleroy** [comment]
Thanks, we'll be discussing this :)

**Comment by benjaminleroy** [comment]
Thank you for the feedback
