### ISSUE TITLE
Final Paper Draft

### ISSUE THREAD

**Issue by janewliang** [berkeley-stat159/project-alpha#144]
Need to write the final draft of the paper and do some organizing. We maybe want to address Ross's Piazza post answer and squish the appendices into a single PDF with the main report. Ideally, we'd all have things written a day or two before the deadline, so there is time to revise and proofread and every section gets more than one pair of eyes checking it. 

Also need to write the scripts to generate the images.

**Comment by benjaminleroy** [comment]
Yeah, we'll have to deal with Ross's response vs Jarrod's response (I emailed Ross some more questions about it too, so we can talk about it tomorrow)

**Comment by janewliang** [comment]
ALL images need to be cached in the top-level images directory. Please also reference images in the paper using the top directory. 

Abstract

Intro

Data

Methods: 
Smoothing
Convolution + time correction
Linear regression (includes model selection)
Normality
Hypothesis testing
Clustering (includes BH, Hiro's clustering, t, beta, and parameter smoothing, in that order)

Results:
This is a single section that gives a general overview of the results. 

Discussion:
Discussion of results: more broad the the results section, also compares w/original paper
Discussion of future work: what it says on the tin.

Appendices:
Outliers
Smoothing
Convolution
Clustering?
TIme series

**Comment by hiroto-udagawa** [comment]
ALL images need to be cached in the top-level images directory. Please also reference images in the paper using the top directory.

Abstract

Intro

Data

Methods: 
Smoothing - RACHEL
Convolution + time correction - BEN
Linear regression (includes model selection) - JANE (model selection - HIROTO+BEN)
Normality - JANE
Hypothesis testing - HIROTO
Clustering (includes BH, Hiro's clustering, t, beta, and parameter smoothing, in that order) - HIROTO, BEN, RACHEL

Results:
This is a single section that gives a general overview of the results. - EVERYONE

Discussion:
Discussion of results: more broad the the results section, also compares w/original paper - EVERYONE
Discussion of future work: what it says on the tin.  - EVERYONE

Appendices:
Outliers - JANE
Smoothing - RACHEL
Convolution - BEN
Clustering? - HIROTO
Time series - JANE

**Comment by janewliang** [comment]
I will update abstract, intro, and data. Will also be fixing the Makefiles and READMEs.

**Comment by reychil** [comment]
I will do t, beta, parameter smoothing (for methods-clustering)..
