### ISSUE TITLE
How to Run the final stuff

### ISSUE THREAD

**Issue by benjaminleroy** [berkeley-stat159/project-alpha#169]
@janewliang @hiroto-udagawa @reychil @kentschen 
### required

smooth_final.py
convolution_final.py
glm_final_fourier.py
bh_t_beta_final_fourier.py
image_overlay_final.py
### some really late "eda"

selection_final_fourier.py
parameter_selection_final_fourier.py

**Comment by janewliang** [comment]
Yeah, will be adding this to the README and Makefile.
