### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by jarrodmillman** [berkeley-stat159/project-alpha#79]
Great work. Keep it up.  Let's know how you can help.

I know you are aware of this, but you need to make it clear to us and
documented that everyone is contributing.  I know you are all participating,
but you should consider trying to switch who is generating code to mostly
reviewing code (or some other approach).

**Comment by janewliang** [comment]
@jarrodmillman Would it be possible for you to give us more specific feedback on the work we've done, beyond just making sure everyone has configured Git correctly?
